# Generated by Django 4.1.3 on 2022-11-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="rating",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
